// Multi-strategy DOM selector builder, per §7.5.
// Falls through priorities; always returns *something*.

import type { SelectorDescriptor } from "./types";

const AUTO_GEN_ID = /(^|[-_])(?:[0-9a-f]{8}|[0-9]{6,}|uuid|hash)/i;

export function buildSelector(el: Element): SelectorDescriptor {
  const tag = el.tagName.toLowerCase();
  const role = el.getAttribute("role");
  const visibleText = ((el as HTMLElement).innerText || el.textContent || "")
    .trim()
    .slice(0, 80);

  const rect = (el as HTMLElement).getBoundingClientRect?.();
  const bbox = rect
    ? { x: Math.round(rect.left), y: Math.round(rect.top), w: Math.round(rect.width), h: Math.round(rect.height) }
    : undefined;

  // 1. data-testid
  const testId = el.getAttribute("data-testid");
  if (testId) {
    return { strategy: "data-testid", selector: `[data-testid="${cssEscape(testId)}"]`, tag, role, visibleText, bbox };
  }

  // 2. id (skip if it looks autogenerated)
  const id = el.getAttribute("id");
  if (id && !AUTO_GEN_ID.test(id)) {
    return { strategy: "id", selector: `#${cssEscape(id)}`, tag, role, visibleText, bbox };
  }

  // 3. aria-label + tag
  const aria = el.getAttribute("aria-label");
  if (aria) {
    return { strategy: "aria-label", selector: `${tag}[aria-label="${cssEscape(aria)}"]`, tag, role, visibleText, bbox };
  }

  // 4. name attribute (form fields)
  const name = el.getAttribute("name");
  if (name) {
    return { strategy: "name", selector: `${tag}[name="${cssEscape(name)}"]`, tag, role, visibleText, bbox };
  }

  // 5. visible text + tag (most useful for buttons/links)
  if (visibleText && /^(button|a|summary|label)$/i.test(tag) && visibleText.length <= 40) {
    return { strategy: "text", selector: `${tag}:contains("${visibleText.replace(/"/g, '\\"')}")`, tag, role, visibleText, bbox };
  }

  // 6. short CSS path (≤ 4 levels, no nth-child)
  return { strategy: "css", selector: shortCssPath(el, 4), tag, role, visibleText, bbox };
}

function shortCssPath(el: Element, maxDepth: number): string {
  const parts: string[] = [];
  let cur: Element | null = el;
  let depth = 0;
  while (cur && depth < maxDepth && cur.nodeType === 1 && cur.tagName.toLowerCase() !== "html") {
    let part = cur.tagName.toLowerCase();
    const cls = (cur.getAttribute("class") || "")
      .split(/\s+/)
      .filter((c) => c && !AUTO_GEN_ID.test(c) && !/^[a-z]+-\d+$/i.test(c))
      .slice(0, 2);
    if (cls.length) part += "." + cls.map(cssEscape).join(".");
    parts.unshift(part);
    cur = cur.parentElement;
    depth++;
  }
  return parts.join(" > ");
}

function cssEscape(s: string): string {
  // Best-effort. Browsers ship CSS.escape but we keep it dependency-free.
  if (typeof CSS !== "undefined" && CSS.escape) return CSS.escape(s);
  return s.replace(/[^a-zA-Z0-9_-]/g, (ch) => "\\" + ch);
}
